# Generated by Django 2.2.3 on 2019-08-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoapp', '0002_auto_20190802_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Dettaglio', 'verbose_name_plural': 'Dettagli'},
        ),
        migrations.AddField(
            model_name='entry',
            name='nome',
            field=models.CharField(default='Cinqueterre', max_length=100),
        ),
    ]
