# Generated by Django 2.2.3 on 2019-08-02 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcoapp', '0003_auto_20190802_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_categoria', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_fase', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fasi',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Punto Dettaglio', 'verbose_name_plural': 'Punti Dettagli'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='nome',
        ),
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('oggetto', models.CharField(max_length=400)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_lavoro', models.DateField(default=datetime.date.today, verbose_name='Data lavori')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcoapp.Categoria')),
            ],
            options={
                'verbose_name': 'Lavoro',
                'verbose_name_plural': 'Lavori',
            },
        ),
        migrations.CreateModel(
            name='Dettaglio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_dettaglio', models.CharField(max_length=200)),
                ('data_dettaglio', models.DateField(default=datetime.date.today, verbose_name='Data dettaglio')),
                ('fase_dettaglio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcoapp.Fase')),
                ('lavoro_dettaglio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcoapp.Lavoro')),
            ],
            options={
                'verbose_name': 'Dettaglio',
                'verbose_name_plural': 'Dettagli',
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_allegato', models.FileField(upload_to='upload/')),
                ('documento_allegato', models.FileField(upload_to='upload/')),
                ('dettaglio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcoapp.Dettaglio')),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
            },
        ),
    ]
