# Generated by Django 2.2.3 on 2019-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoapp', '0004_auto_20190802_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='nome',
            field=models.CharField(default='cinqueterre', max_length=100),
        ),
    ]
