# Generated by Django 2.2.3 on 2019-08-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcoapp', '0006_dettaglio_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglio',
            name='point',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='parcoapp.Entry'),
        ),
    ]
