# Generated by Django 2.2.3 on 2019-08-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcoapp', '0008_auto_20190802_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglio',
            name='point',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='parcoapp.Entry'),
        ),
    ]
